name: Test Local Action

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test-local-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          api-url: ${{ vars.GCLOUD_API_URL }}
          api-token: ${{ secrets.GCLOUD_API_TOKEN }}
          project-id: ${{ vars.GCLOUD_PROJECT }}
          region-id: ${{ vars.GCLOUD_REGION }}
          name: test-container
          image: nginx:alpine

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.address }}"
